// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHlOmzmv5G5IrNw7sFoq06AhlDPF6UsV4',
    appId: '1:661700431102:android:7f3921e41e5bd8457629af',
    messagingSenderId: '661700431102',
    projectId: 'quick-meet-476fa',
    storageBucket: 'quick-meet-476fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtAwh9zrsGxyRKhvFSVUB9e9XicPFTPxA',
    appId: '1:661700431102:ios:4e2471093cbe65ed7629af',
    messagingSenderId: '661700431102',
    projectId: 'quick-meet-476fa',
    storageBucket: 'quick-meet-476fa.appspot.com',
    androidClientId: '661700431102-adsqjslu1u0bcs4896dn7gvnf9u35osh.apps.googleusercontent.com',
    iosClientId: '661700431102-4pin47osu525dabs0piovafr781pirqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickMeet',
  );
}
